name: Deploy benchrunner to AWS

on:
  workflow_dispatch:
    inputs:
      register_token:
        description: Registration token for the self-hosted runner.
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
        with:
          repository: 2024-mlh-cinder/bench_runner-terraform

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Start EC2 instance Using Terraform Configuration
        run: |
          terraform init
          terraform apply -auto-approve -input=false -var register_token="${{ inputs.register_token }}"
